//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.ThongTinHoaDons = new HashSet<ThongTinHoaDon>();
        }
    
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<long> MaND { get; set; }
        public string DiaChi { get; set; }
        public long MaHD { get; set; }
    
        public virtual ICollection<ThongTinHoaDon> ThongTinHoaDons { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
