//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ThongTinHoaDons = new HashSet<ThongTinHoaDon>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<long> Gia { get; set; }
        public string MoTa { get; set; }
        public string XuatXu { get; set; }
        public string MaDM { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual ICollection<ThongTinHoaDon> ThongTinHoaDons { get; set; }
    }
}
